import json
from pathlib import Path
from types import SimpleNamespace

import pytest

from aviation_agentic_ai.ontology.cq import build_cq_prompt, normalize_cq_artifact
from aviation_agentic_ai.ontology.generation import (
    SRDArtifact,
    TIPArtifact,
    build_initial_ttl_content,
    generate_ontology,
    verify_generated_candidate_quality,
)
from aviation_agentic_ai.ontology.profiles import get_domain_profile
from aviation_agentic_ai.ontology.validation import verify_turtle_text


def test_aviation_profile_builds_cq_prompt() -> None:
    profile = get_domain_profile("aviation_phak")
    prompt = build_cq_prompt("Lift is generated by airflow over an airfoil.", profile)

    assert "PHAK" in profile.display_name
    assert "Competency Questions" in prompt
    assert "Lift" in prompt


def test_initial_ontology_is_valid_turtle() -> None:
    ttl = build_initial_ttl_content("aviation_phak")
    valid, message = verify_turtle_text(ttl)

    assert valid, message
    assert ":Cl_Airfoil a owl:Class" in ttl


def test_generate_ontology_dry_run_writes_seed(tmp_path: Path) -> None:
    cq_path = tmp_path / "cqs.json"
    output_path = tmp_path / "generated.ttl"
    cqs = normalize_cq_artifact(
        {
            "doc": {
                "0": [
                    {
                        "competency_question": "What class represents an airfoil?",
                        "key_entities": ["airfoil"],
                        "odp_hint": "Taxonomy",
                        "expected_answer": "Airfoil",
                    }
                ]
            }
        }
    )
    cq_path.write_text(json.dumps(cqs) + "\n", encoding="utf-8")

    result = generate_ontology(
        pdf_path="data/raw/06_phak_ch4_0.pdf",
        cq_path=cq_path,
        output_path=output_path,
        dry_run=True,
    )

    assert result.rdf_valid
    assert output_path.exists()
    assert "Cl_PrinciplesOfFlight" in output_path.read_text(encoding="utf-8")


def test_srd_and_tip_artifact_schema_validation() -> None:
    srd = SRDArtifact.model_validate(
        {
            "cq_ids": ["cq-1"],
            "source_page": 0,
            "evidence_quotes": ["Lift is generated by airflow."],
            "key_concepts": ["Lift", "Airflow"],
        }
    )
    tip = TIPArtifact.model_validate(
        {
            "classes": ["Cl_Lift"],
            "properties": ["affects"],
            "axiom_plan": ["Cl_Lift subclassOf Cl_AerodynamicForce"],
            "domain_range_plan": ["affects domain Cl_AerodynamicCause range Cl_AerodynamicEffect"],
            "risk_flags": [],
        }
    )

    assert srd.source_page == 0
    assert tip.classes == ["Cl_Lift"]

    try:
        SRDArtifact.model_validate({"cq_ids": [], "source_page": 0, "evidence_quotes": []})
    except ValueError as exc:
        assert "at least 1 item" in str(exc) or "List should have at least 1 item" in str(exc)
    else:
        raise AssertionError("SRD schema should reject empty required arrays")


def test_dry_run_manifest_excludes_secrets(tmp_path: Path, monkeypatch) -> None:
    pdf_path = tmp_path / "source.pdf"
    cq_path = tmp_path / "cqs.json"
    output_path = tmp_path / "generated.ttl"
    artifact_dir = tmp_path / "artifacts"
    pdf_path.write_bytes(b"not a real pdf but hashable")
    cqs = normalize_cq_artifact(
        {
            "doc": {
                "0": [
                    {
                        "competency_question": "What class represents lift?",
                        "key_entities": ["lift"],
                        "odp_hint": "Taxonomy",
                        "expected_answer": "Lift",
                    }
                ]
            }
        }
    )
    cq_path.write_text(json.dumps(cqs) + "\n", encoding="utf-8")
    monkeypatch.setenv("LLM_PROVIDER", "openai")
    monkeypatch.setenv("MODEL_NAME", "gpt-test")
    monkeypatch.setenv("OPENAI_BASE_URL", "https://token.example.com/v1")
    monkeypatch.setenv("OPENAI_API_KEY", "sk-test-secret")
    monkeypatch.setenv("DEEPSEEK_API_KEY", "deepseek-secret")

    result = generate_ontology(
        pdf_path=pdf_path,
        cq_path=cq_path,
        output_path=output_path,
        dry_run=True,
        artifact_dir=artifact_dir,
        run_id="test-run",
    )

    manifest_text = (artifact_dir / "manifest.json").read_text(encoding="utf-8")
    manifest = json.loads(manifest_text)
    assert result.rdf_valid
    assert not Path(manifest["inputs"]["pdf_path"]).is_absolute()
    assert not Path(manifest["inputs"]["cq_path"]).is_absolute()
    assert not Path(manifest["output_path"]).is_absolute()
    assert manifest["llm"]["base_url_host"] == "token.example.com"
    assert "sk-test-secret" not in manifest_text
    assert "deepseek-secret" not in manifest_text
    assert "OPENAI_API_KEY" not in manifest_text


def test_non_dry_run_manifest_records_llm_failure(tmp_path: Path, monkeypatch) -> None:
    from aviation_agentic_ai.ontology import generation
    from aviation_agentic_ai.llm import providers

    cq_path = tmp_path / "cqs.json"
    output_path = tmp_path / "generated.ttl"
    artifact_dir = tmp_path / "artifacts"
    cqs = normalize_cq_artifact(
        {
            "doc": {
                "0": [
                    {
                        "competency_question": "What class represents lift?",
                        "key_entities": ["lift"],
                        "odp_hint": "Taxonomy",
                        "expected_answer": "Lift",
                    }
                ]
            }
        }
    )
    cq_path.write_text(json.dumps(cqs) + "\n", encoding="utf-8")

    class FailingLLM:
        def invoke(self, _messages):
            raise RuntimeError("model denied")

    monkeypatch.setattr(
        generation,
        "extract_pages",
        lambda *_args, **_kwargs: [SimpleNamespace(page_number=0, text="Lift needs airflow.")],
    )
    monkeypatch.setattr(providers, "get_llm", lambda **_kwargs: FailingLLM())

    with pytest.raises(RuntimeError, match="Failed to generate validated SRD/TIP"):
        generate_ontology(
            pdf_path="data/raw/06_phak_ch4_0.pdf",
            cq_path=cq_path,
            output_path=output_path,
            artifact_dir=artifact_dir,
            run_id="failing-run",
            max_qa_cycles=0,
        )

    manifest = json.loads((artifact_dir / "manifest.json").read_text(encoding="utf-8"))
    assert manifest["failed_pages"][0]["stage"] == "srd_tip_validation"
    assert "model denied" in manifest["failed_pages"][0]["message"]


def test_generated_candidate_quality_gates_preserve_terms() -> None:
    previous = """@prefix : <http://www.example.org/aviation/phak#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

: a owl:Ontology .
:Cl_Thing a owl:Class .
:Cl_ChildThing a owl:Class ;
    rdfs:subClassOf :Cl_Thing .
:hasChild a owl:ObjectProperty ;
    rdfs:domain :Cl_Thing ;
    rdfs:range :Cl_ChildThing .
"""
    candidate = previous + "\n:Cl_ExtraThing a owl:Class ; rdfs:subClassOf :Cl_Thing .\n"
    deleted_candidate = previous.replace(":Cl_ChildThing a owl:Class ;", ":Cl_RemovedThing a owl:Class ;")

    valid, message = verify_generated_candidate_quality(candidate, previous)
    deleted_valid, deleted_message = verify_generated_candidate_quality(deleted_candidate, previous)

    assert valid, message
    assert not deleted_valid
    assert "deleted existing schema terms" in deleted_message


def test_generated_candidate_quality_accepts_ontology_declaration() -> None:
    ttl = """@prefix : <http://www.example.org/aviation/phak#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

: a owl:Ontology ;
    rdfs:label "Test ontology" .

:Cl_Thing a owl:Class ;
    rdfs:label "Thing" .

:hasThing a owl:ObjectProperty ;
    rdfs:label "has thing" ;
    rdfs:domain :Cl_Thing ;
    rdfs:range :Cl_Thing .
"""

    valid, message = verify_generated_candidate_quality(ttl, ttl)

    assert valid, message
