from pathlib import Path

from aviation_agentic_ai.evaluation.document_metadata import document_metadata_from_pdf
from aviation_agentic_ai.utils import pdf as pdf_utils


class FakePage:
    def __init__(self, text: str) -> None:
        self.text = text
        self.modes: list[str] = []

    def get_text(self, mode: str) -> str:
        self.modes.append(mode)
        return self.text


class FakeDocument:
    def __init__(self, pages: list[FakePage]) -> None:
        self.pages = pages
        self.entered = False
        self.closed = False

    def __enter__(self) -> "FakeDocument":
        self.entered = True
        return self

    def __exit__(self, *_args: object) -> None:
        self.closed = True

    def __iter__(self):
        return iter(self.pages)


def test_extract_pages_skips_empty_pages_and_preserves_zero_based_numbers(monkeypatch) -> None:
    pages = [
        FakePage(""),
        FakePage("   \n"),
        FakePage("Lift is generated by pressure differences."),
        FakePage("Drag opposes motion."),
    ]
    opened_paths: list[str] = []
    fake_document = FakeDocument(pages)

    def fake_open(path: str) -> FakeDocument:
        opened_paths.append(path)
        return fake_document

    monkeypatch.setattr(pdf_utils.fitz, "open", fake_open)

    result = list(pdf_utils.extract_pages(Path("data/raw/handbook.pdf")))

    assert opened_paths == ["data/raw/handbook.pdf"]
    assert fake_document.entered
    assert fake_document.closed
    assert [(page.page_number, page.text) for page in result] == [
        (2, "Lift is generated by pressure differences."),
        (3, "Drag opposes motion."),
    ]
    assert [page.modes for page in pages] == [["text"], ["text"], ["text"], ["text"]]


def test_extract_pages_respects_max_pages_before_text_extraction(monkeypatch) -> None:
    pages = [
        FakePage("First page."),
        FakePage("Second page."),
        FakePage("Third page should not be read."),
    ]

    monkeypatch.setattr(pdf_utils.fitz, "open", lambda _path: FakeDocument(pages))

    result = list(pdf_utils.extract_pages("handbook.pdf", max_pages=2))

    assert [(page.page_number, page.text) for page in result] == [
        (0, "First page."),
        (1, "Second page."),
    ]
    assert pages[2].modes == []


def test_document_metadata_defaults_and_overrides_use_stable_relative_paths() -> None:
    defaulted = document_metadata_from_pdf("data/raw/06_phak_ch4_0.pdf")
    overridden = document_metadata_from_pdf(
        "data/raw/custom_source.pdf",
        document_id="custom-doc",
        title="Custom Source",
        source_type="local_test_pdf",
        chapter="appendix",
        revision_date="2026-05-30",
        page_start=3,
        page_end=9,
    )

    assert defaulted.to_dict() == {
        "document_id": "06_phak_ch4_0",
        "title": "06 phak ch4 0",
        "source_type": "faa_handbook_chapter",
        "source_path": "data/raw/06_phak_ch4_0.pdf",
        "chapter": "4",
        "revision_date": None,
        "page_start": None,
        "page_end": None,
    }
    assert overridden.to_dict() == {
        "document_id": "custom-doc",
        "title": "Custom Source",
        "source_type": "local_test_pdf",
        "source_path": "data/raw/custom_source.pdf",
        "chapter": "appendix",
        "revision_date": "2026-05-30",
        "page_start": 3,
        "page_end": 9,
    }
